---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-storage
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Ti
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "fstab/cifs"
    readOnly: false
    fsType: "cifs"
    secretRef:
      name: "elk-cifs-secret"
    options:
      networkPath: "//172.28.109.204/data/k8s/elk"
      mountOptions: "dir_mode=0777,file_mode=0777,noperm,cache=none"