---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-storage-pvc
  namespace: kube-elk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: elk-storage