apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
  namespace: kube-elk
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    node.name: ${POD_NAME}
    config.reload.automatic: true
    config.reload.interval: 3s
  logstash.conf: |
    input {
      tcp {
        port => 5055
        mode => server
        codec => json_lines
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "logstash-%{+YYYY.MM.dd}"
      }
      stdout{
        codec => json_lines
      }
    }
    
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: kube-elk
spec:
  ports:
    - port: 5055
      targetPort: 5055
      name: http-port
  selector:
    app: logstash
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: kube-elk
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
      matchLabels:
        app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      hostname: logstash
      containers:
      - name: logstash
        image: docker-registry.dhc:5000/logstash:7.5.1
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: logstash-config
            mountPath: /usr/share/logstash/config/logstash.yml
            subPath: logstash.yml
          - name: logstash-config
            mountPath: /usr/share/logstash/pipeline/logstash.conf
            subPath: logstash.conf
          - name:  logstash-volume
            mountPath:  /usr/share/logstash/data/
            subPath: logstash/data/
        ports:
          - name: http-port
            containerPort: 5055
      volumes:
        - name: logstash-config
          configMap:
            name: logstash
        - name: logstash-volume
          persistentVolumeClaim:
            claimName: elk-storage-pvc