---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: slw
  labels: 
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.28
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: TZ
            value: "Asia/Shanghai"
        ports:
          - name: mysql-port
            containerPort: 3306
            hostPort: 3306
        args:
          - --character-set-server=utf8
          - --max_connections=1000
          - --innodb_buffer_pool_size=6G
        
        volumeMounts:
          - name:  mysql-volume
            mountPath:  /var/lib/mysql
            subPath: mysql
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: slw-storage-pvc
      
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: slw
spec:
  selector:
    app: mysql
  ports:
  - name: mysql-port
    port: 3306
    targetPort: mysql-port
