---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: slw
  labels: 
    app: tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:7.0.99
        ports:
          - name: tomcat
            containerPort: 8080
            hostPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: tomcat
  namespace: slw
spec:
  selector:
    app: tomcat
  ports:
  - name: tomcat
    port: 8080
    targetPort: tomcat

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tomcat
  namespace: slw
spec:
  rules:
  - host: tomcat.slw
    http:
      paths:
      - backend:
          serviceName: tomcat
          servicePort: tomcat