kind: Service
apiVersion: v1
metadata:
  name: testt
  namespace: slw
spec:
  ports:
  - port: 8887
    targetPort: 8887

---   
apiVersion: v1
kind: Endpoints
metadata:
  name: testt
  namespace: slw
subsets:
  - addresses:
      - ip: 172.28.108.158
    ports:
      - port: 8887
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testt
  namespace: slw
spec:
  rules:
  - host: testt.slw
    http:
      paths:
      - backend:
          serviceName: testt
          servicePort: 8887
